### ISSUE TITLE
Geocoding

### ISSUE THREAD

**Issue by DataWookie** [marinuslouw/travelling-salesman-problem#1]
Hi Marinus,

Wow, I had completely forgotten about that blog post. Rather flattered that you found it (and used it).

However, at the same time, the objective here was to see how *you* solve problems. I'm happy with the changes that you have made, but I'd like you to do one more thing: you currently have the location coordinates hard coded into the script. Can you please write some code to get those locations programmatically?

Incidentally, Megan has just given me rather favourable feedback on your conversation today.

Thanks,
Andrew.

**Comment by marinuslouw** [comment]
Hi Andrew, 

Only saw your comment now. Don't know why I didn't get a notification via email.

Yes sure. 

Chat soon,
Marinus

**Comment by DataWookie** [comment]
Good work!
